services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - /Users/mehdirhouzlane/data-feed-node/.chainlink-goerli/data:/var/lib/postgressql/data/

  chainlink:
    image: "smartcontract/chainlink:1.3.0"
    env_file:
      - .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      - /Users/mehdirhouzlane/data-feed-node/.chainlink-goerli/chainlink-volume:/chainlink
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt
    

